### ISSUE TITLE
Error: watch ENOSPC

### ISSUE THREAD

**Issue by AntonTrapp** [foreverjs/forever-monitor#111]
Tying to start a simple nodejs program with forever (runs when called from node) like this:

```bash
NODE_ENV=production forever --minUptime=1000 --spinSleepTime=1000 -l /u/logs/scad3_forever.log -o /u/logs/scad3_out.log -e /u/logs/scad3_err.log scad3/server/scad3.json
```

Get the error message:

```bash
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch ENOSPC
    at errnoException (fs.js:1028:11)
    at FSWatcher.start (fs.js:1060:11)
    at Object.fs.watch (fs.js:1085:11)
    at createFsWatchInstance (/usr/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleFile (/usr/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/forever/node_modules/forever-monitor/node_modules/chokidar/lib/nodefs-handler.js:468:21)
    at Object.oncomplete (fs.js:107:15)
```

```bash
/dev/sda5       8.2G  2.3G  5.5G  30% /
```
5GB not enough? How much do I need to use forever-monitor? And why does it need so much disk space???

Thank you very much in advance and kind regards,
Anton

**Comment by AntonTrapp** [comment]
Seems to have nothing to do with the free space, but with the number of files being watched.

Solution (for Debian, Ubuntu, ..:):

```bash
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```
Source:

http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

If anybody is searching for that, seems a common problem. Maybe it should be put into the readme.
